# Generated by Django 2.0.9 on 2019-10-23 05:53

import django.core.validators
from django.db import migrations, models
import todoapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled', max_length=40, unique=True)),
                ('date_time', models.DateTimeField(default=todoapp.models.get_now, validators=[todoapp.models.no_future])),
                ('text', models.TextField()),
                ('link_code', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('lang', models.CharField(choices=[('text', 'No'), ('java', 'Yes')], default='text', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
