# Generated by Django 2.0.9 on 2019-10-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='lang',
            field=models.CharField(choices=[('text', 'No'), ('c', 'Yes')], default='text', max_length=10),
        ),
    ]
